### ISSUE TITLE
Add zero scaling: false attribute to charts configs

### ISSUE THREAD

**Issue by Mikhail-iontsev** [OHDSI/Ares#105]
**Is your feature request related to a problem? Please describe.**
Some charts are not as visually descriptive due to slight changes in values between data points. 

**Describe the solution you'd like**
This could easily be solved by changing initial scaling value of a chart from zero to the lowest in the dataset.

Before: 
![dataQuality1](https://user-images.githubusercontent.com/92372420/158468085-9ef85b80-7688-4585-9412-f305a240b884.png)

After: 
![dataQuality2](https://user-images.githubusercontent.com/92372420/158468129-09dba7a5-910f-4611-9c6e-d532a6fb85d3.png)

**Comment by fdefalco** [comment]
There is a bit of a debate on this topic in the visualization communities.   Here's a quick discussion I found - 
https://thenode.biologists.com/non-zero-baselines-the-good-the-bad-and-the-ugly/resources/

Usually I am opposed to a non-zero baseline on the y-axis.  This article argues it can be helpful  with line charts like you are suggesting here in this 'after' plot.  I don't think its a problem with this particular report, but on something like the domain continuity report, it could become more misleading unless all the plots share the same scale on the y-axis.  

I'm not opposed to this particular suggestion, but with the work you are doing to standardize the charting throughout the application, this is something to be aware of before applying it across all charts.

Let me know what you think.

**Comment by Mikhail-iontsev** [comment]
The point of standardization is to make similar charts feel similar for the user, meaning they should at least try to share functionality if possible. This should not however impact our decision to use or not to use the non-zero baseline since our goal is to provide the data in the most descriptive way possible. Thus, this decision should be driven only by data.

All line charts that are not to be compared to any other charts will probably benefit from the non-zero baseline, while the others should be left as they are.

There's another solution. Since the app is growing, i believe it would be a good idea to make a settings menu in the future so that we could give the user more options, like for example choosing the baseline type or even turning on night mode.

**Comment by fdefalco** [comment]
I agree, a settings menu would be useful.  I'll add items to the backlog project to track your suggestions.
