### ISSUE TITLE
pivot table viewer

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#115]
Introduce a pivot table viewer component to the ARES application.  The initial use of this view will be to allow a user view the number of data quality issues by different attributes.  For example, number of failures by Table or other grouping such as category.  Ideally a standard pivot table could be used instead of developing one from scratch.  

Once integrated this view should replace the existing Data Quality report view but still allow a user to navigate to the current detailed view that includes the sql query and other details for an individual failure.

**Comment by fdefalco** [comment]
The overview tab can remain the same, but a new tab can provide the pivot table experience.

A standard pivot table typically allows the user to create summary slice/dice type operations to aggregate the total counts along different dimensions of the data.  An example can be found here:  https://github.com/Click2Buy/vue-pivot-table

I think it could be simpler in the way you are describing using the v-data-table component with a row to provide a group-by capability and this may be simpler than integration of an additional library.

**Comment by Mikhail-iontsev** [comment]
It's actually much easier to use an existing library like vue-pivottable which would provide a full pivot table experience (https://github.com/Seungwoo321/vue-pivottable). Here's a screen of already integrated functionality
![Screenshot from 2022-04-19 07-36-46](https://user-images.githubusercontent.com/92372420/163921525-fb4b1b03-327f-40a6-ba49-ccce056f197a.png)

**Comment by fdefalco** [comment]
That looks great.  I'm tagging @clairblacketer in case she has any feedback.  I think this would be a great solution.
