### ISSUE TITLE
feasibility tool issue

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#130]
The concept requirements section currently has an option for Observation Period, this should be Observation, not observation period.

![image](https://user-images.githubusercontent.com/6586384/169144476-0f5fd2a9-651b-4a33-ada3-3c748a5398c3.png)

**Comment by Mikhail-iontsev** [comment]
Both required and desired domains too have the Observation Period option. Should i rename them too?

**Comment by fdefalco** [comment]
Correct, there was initially a bug in the domain analysis script that was looking at observation period, this is supposed to be using the observation table results
