### ISSUE TITLE
tooltip showing wrong series name on mouse hover

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#155]
on the domain density report mousing over the measurement series shows the condition era domain name in the tooltip

![image](https://user-images.githubusercontent.com/6586384/181800262-e2af8b0a-df89-43c3-ae11-1c1d77d3a843.png)

**Comment by Mikhail-iontsev** [comment]
This is actually expected behavior, but the lack of the ruler isn't. By default if no domain was chosen in the legend the tooltip would show the highest value on the Y axis (this behavior is applied to all charts with a ruler and legend selection).
