### ISSUE TITLE
"Drug Domain Stratification by Drug Type" instead of "Domain Data Stratification by Visit" in Visit Occurrence report in Ares Beta

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Ares#168]
There's a "Drug Domain Stratification by Drug Type" graph in the Visit Occurrence report instead of "Domain Data Stratification by Visit".
Issue exists only in beta version. 
Main version is fine

**Comment by fdefalco** [comment]
This stratification should only appear on the drug domain report.
