### ISSUE TITLE
improvements: data source release / observation period report

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#173]
cumulative observation chart: show 2 digits of precision after decimal for % of people in tooltip

years of observation by age chart: add min/max p10/p90 button toggle, hide categoryOrder variable from tooltip

years of observation by sex: add min/max p10/p90 button toggle

age at first observation: show 2 digits of precision after decimal for % of people in tooltip

age at first observation by sex: add min/max p10/p90 button toggle to chart

Should we consider adding the min/max p10/p90 toggle to settings the same way we do with zero baseline?

**Comment by Mikhail-iontsev** [comment]
Moving those buttons would look better in the code, but would it be convenient for the users to open the settings menu each time they need to change values?

**Comment by fdefalco** [comment]
True, but it is mostly a personal preference when you are looking at the box and whisker plots.   Personally I always want to see 10/90 because the min/max aren't always very informative.  So it would be something you only typically change one time and leave it that way.
