### ISSUE TITLE
some box/whisker plots not responding to global min/max p10/p90 setting

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#179]
Box and whisker plots other than the measurement value chart do not seem to be responding to the global setting for p10/p90.

Seeing this in several charts:

#/cdm/<Source>/<release>/condition_occurrence/<concept id>- age at first diagnosis chart
#/cdm/<Source>/<release>/measurement/<concept id> - age at first occurrence chart

appears to be inconsistent with measurement report.

**Comment by Mikhail-iontsev** [comment]
Only the charts mentioned in the issue + those that had the button earlier https://github.com/OHDSI/Ares/issues/173 are affected by this setting.

I can add it to other charts. As far as I understand those should be all the bar charts using the p10/p90 and min/max values.
