### ISSUE TITLE
Measurement Value Distributions is not informative enough

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Ares#211]
The numerical range of measurement values hugely varies depending on the units used, and even within one unit it varies a lot due to mistakenly recorded outliners. So this graph becomes hard or impossible to read - small values aren't shown - there's basically no place to hover to get the result.
[Here, for example  ](https://epibeta.jnj.com/ARES/#/cdm/AMBULATORY_EMR/20220830/measurement/3010910)
![image](https://user-images.githubusercontent.com/8568959/213446375-2d99301a-591a-4ae5-8c14-99e0bc7585f6.png)

Is it possible to add the tabular view including column with counts, so the user can sort by count,
or add the option to show the N most frequently used units in a graph? - this might not work perfectly as there might be results measured in thousand/ml and million/ml, for example, for the same measurement, and values will be 1000 times different

**Comment by fdefalco** [comment]
Add a tabular view to the data source release measurement concept report.  Similar to what appears o the network measurement report.  (#/cdm/DATA_SOURCE/DATA_SOURCE_RELEASE/measurement/CONCEPT_ID)

**Comment by fdefalco** [comment]
A table is now available on the report to make this easier to interpret.
