### ISSUE TITLE
metadata support

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#225]
introduce support for a new metadata system that will allow key event descriptions to be overlayed on existing charts with date ranges on the x axis.

UI example is well implemented in google finance.  Key events are shown at the base of the x-axis with the event descriptions displayed in a display below the chart.  

![image](https://user-images.githubusercontent.com/6586384/220659018-239e4ed5-4169-47e7-8f4e-e9d0f40ec52e.png)

Metadata will be provided by a newly specified set of files that contain the necessary information.

**Comment by ssamus** [comment]
The task is done, merged to the Development branch.
