### ISSUE TITLE
charts do not resize dynamically on horizontal resize

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#23]
ares/#/_network/dataquality

**Comment by Mikhail-iontsev** [comment]
Hi!

Do i understand correctly that you need all the project's charts to be able to be resized horizontally (not only the dataquality charts)?

**Comment by fdefalco** [comment]
Yes, that would be ideal, many of the visualizations are wrapped in responsive containers and do currently resize.

**Comment by Mikhail-iontsev** [comment]
Hi!

I'm currently struggling with replicating the issue: the charts do resize horizontally in the dataQuality report (as in all the others i've tested). I've tested this in Safari, Chrome and Firefox. Could you please describe the issue in a more detailed way (or maybe provide the steps to replicate it).

**Comment by fdefalco** [comment]
Ok, I find it hard to reproduce as well..  It seems to only occur with a large number of data sources in the network summary AND if the width is small enough to prevent resize.  I've attached an image to show what is happening. 

![image](https://user-images.githubusercontent.com/6586384/141849877-0244d87a-6921-4c2f-bb26-784a004097d4.png)

This might have something to do with the legend positioning, or a forced margin on the right side of the chart.
