### ISSUE TITLE
theme error

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#235]
![image](https://user-images.githubusercontent.com/6586384/221944284-cd565a27-5df1-48de-a61e-cd4a9e1779c7.png)

Theme support introduced error.

**Comment by Mikhail-iontsev** [comment]
Everything's working in my environment. 

Could you please clear the local storage for ares and update the page?

**Comment by Mikhail-iontsev** [comment]
update: I found the reason of the error. The old version of local storage doesn't include the theme field which results in an error. In order to fix that you can just select a theme in the settings or clear the local storage.

**Comment by fdefalco** [comment]
Thanks, that resolved the issue.
