### ISSUE TITLE
box and whisker tooltip showing limited information

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#238]
![image](https://user-images.githubusercontent.com/6586384/222220842-0664ccc9-0c8b-47dd-bb78-ddb0d4f593fc.png)

I believe this tooltip should also show the 10/90/50 IQR numbers, currently only showing 25/75.

**Comment by Mikhail-iontsev** [comment]
As far as I understand the 50 value should be available in the MEDIAN_VALUE field right? 

Should I also add the MIN_VALUE and MAX_VALUE fields to the tooltip?

**Comment by fdefalco** [comment]
Correct and yes.
