### ISSUE TITLE
npm fibers error

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Ares#241]
**Describe the bug**
Trying to install ares (on Mac M1) using the npm steps, but seeing this error:

```
npm ERR! ../src/fibers.cc:27:65: error: no member named 'kFinalizer' in 'v8::WeakCallbackType'
npm ERR!                 handle.SetWeak(val, WeakCallbackShim<F, P>, WeakCallbackType::kFinalizer);
npm ERR!                                                             ~~~~~~~~~~~~~~~~~~^

```

**To Reproduce**
1. Try npm installation on a Mac
2. See error above

**Expected behavior**
Installs cleanly on a Mac M1.

**Desktop (please complete the following information):**
 - Mac M1

**Comment by Mikhail-iontsev** [comment]
Hi!

Please try running the Development branch of the project. The fibers package is removed from package.json so the issue shouldn't appear.

Please also make sure you're using node version >=16
