### ISSUE TITLE
help icon failure

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#244]
It doesn't seem like the help system currently functions. 

![image](https://user-images.githubusercontent.com/6586384/225382739-4924fa02-8a01-4bed-be44-1917340b8b83.png)

**Comment by Mikhail-iontsev** [comment]
I didn't manage to recreate the error, everything works fine for me in both dev and production modes.

Could you please send me the full address of the index file that the app is trying to access?

**Comment by fdefalco** [comment]
This issue was occurring when the web server did not have permission to serve the markdown file.
