### ISSUE TITLE
annotation / metadata feedback

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#250]
- [x] add a cancel button on the annotation edit screen along with the existing Save button
- [x] add primary and warning styles to to the save and cancel button respectively
- [x] add confirmation to note delete button
- [x] use brighter color for selection area, difficult to see in dark mode especially, perhaps less transparency
- [x] make annotation control on/off a slider similar to the dark/light mode toggle
- [x] add a settings window option for annotations to be on/off by default for charts on reports
- [x] Hide notes when clicking on chart area where there is no annotation
- [x] Option to show all notes in bottom panel for all annotations
- [x] confirm that a note position is based on values and not pixel locations
- [x] show number next to annotations toggle to inform the user if any exist for a chart

**Comment by ssamus** [comment]
The task is done, merged to the Development branch.
