### ISSUE TITLE
A TypeError on page dataQuality

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#314]
TypeError: Cannot read properties of undefined (reading 'data')
    at /ares/src/widgets/pivot/ui/Pivot.vue:65:58
    at Array.reduce (<anonymous>)
    
 **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
    
 **Screen resolution:** 1728 x 1117

**Comment by Mikhail-iontsev** [comment]
Did the error occur as soon as you loaded the page or it happened due to some action on the page? 

I've been yet unable to reproduce the issue using 3 different sources: with correct data, with old format data and with no data.

**Comment by fdefalco** [comment]
I'm having a hard time recreating. I'll open again if I hit it.
