### ISSUE TITLE
network overview issues

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#326]
On the network overview report the main data sources table appears to be showing the wrong column names

![image](https://github.com/OHDSI/Ares/assets/6586384/9c6316fc-28df-4dd8-8e20-aed0d0e28d14)

Additionally clicking on the data source name throws an error:

![image](https://github.com/OHDSI/Ares/assets/6586384/ecc5b640-3215-4301-98b1-83e89e2805f5)

**Comment by Mikhail-iontsev** [comment]
I was unable to reproduce the error. Could you please try again after the fixes?
