### ISSUE TITLE
Add data quality delta report

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Ares#376]
The existing data quality graph over time is nice but is difficult to tell what issues are *new* issues. Example of graph below:
![Screenshot 2024-04-05 at 3 14 09 PM](https://github.com/OHDSI/Ares/assets/7452282/9a6aa296-aee2-4543-8ef7-b4cf7b3a884b)

**Describe the solution you'd like**
When evaluating a data source, it would be nice to:
- Indicate what # or % of issues are *new* issues since the last data quality run in graph form
- Discretely list those new data quality issues. 

This would assist a user to prioritize the investigation of those new issues.

**Describe alternatives you've considered**
To date, determining what issues are new requires opening ARES in two tabs, filtering for a given table and comparing rows manually.

**Comment by fdefalco** [comment]
Once this analysis is completed we can implement this feature. 

https://github.com/OHDSI/AresIndexer/issues/48
