### ISSUE TITLE
Logic and configs separation

### ISSUE THREAD

**Issue by Mikhail-iontsev** [OHDSI/Ares#58]
At the moment project's components include markup, logic, configs and styles which is hard to read and maintain. It would be a good idea to at least separate Vega configs and routes into separate files.

**Comment by fdefalco** [comment]
So create a separate location for the vega specifications?

**Comment by Mikhail-iontsev** [comment]
Yes, it should simplify configs maintenance + make the components more readable.

**Comment by fdefalco** [comment]
My only concern is some cases where there may be dynamic injection into the specifications, but I imagine this would not be an issue?

**Comment by Mikhail-iontsev** [comment]
It shouldn't be an issue at the moment, but will be in the future as i'm thinking of creating a separate reusable graph component which will be displaying data according to the configs loaded into it. This will help us reduce the amount of views to basically one container displaying reusable components. The controller will decide what components (like tables or vega graphs) should be displayed
