### ISSUE TITLE
Utilize VueX

### ISSUE THREAD

**Issue by Mikhail-iontsev** [OHDSI/Ares#59]
As most components share a lot of similar state values it would be a good idea to utilize global store so that the app could become more modular. For example, the error component is currently used in most of components and is loaded if the local componentFailed value equals "true". The problem is that we're forced to use the Error component in each of components that could fail to load data.

A better approach would be to make this value global, create an additional wrapper component that will display the loaded data or the required component according to the global componentFailed value.

**Comment by fdefalco** [comment]
I'm in support of this change.
