### ISSUE TITLE
Sort the Observation periods per person report by % of people

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Ares#78]
**Describe the solution you'd like**
The report that lists the number of observation periods per person is sorted by number of observation periods rather than by % of people, making it difficult to read. 

**Describe alternatives you've considered**
Either changing the default sort or allowing the user to sort on the columns would be helpful

**Additional context**
![image](https://user-images.githubusercontent.com/12911960/148127689-4f31a28f-69d0-4936-9793-d55c88bb5712.png)

**Comment by fdefalco** [comment]
This was resolved in a prior bug fix, hasn't been pushed to our environment yet.

**Comment by clairblacketer** [comment]
Thanks so much!
