### ISSUE TITLE
show loading indicator on explorer selection change

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#94]
On the table based reports (drugs, condition, observations, etc) the table updates correctly upon making a change in the selector, however this is no indication that loading is occurring or when it has completed often making it difficult to notice when the data has updated.

Suggest returning to loading state while the update occurs to make this more clear.

**Comment by Mikhail-iontsev** [comment]
Unfortunately, i couldn't reproduce the issue using the code from the main branch. The issue in question was solved in https://github.com/OHDSI/Ares/pull/75.  Are you sure you're using the latest version in your environment?
